---
#Stores database login details and crypto secrets. `insec_user` MUST start at line 6, `sec_user` MUST start at line 18, `cryptographic pepper`MUST start at line 30.
Users:
#Limited permissions, only for pulling data from the server. Used by users.
#Perms: SELECT, INSERT for login table only in the event a user is registering for an account.
    insec_user:
        host:
            localhost
        username:
            sec_user
        password:
            greenChair153
        database:
            pythonsweb

#for pushing/pulling from/to the server. Used by admins.
#Perms: SELECT,INSERT,UPDATE,DELETE.
    sec_user:
        host:
            localhost
        username:
            sec_user
        password:
            greenChair153
        database:
            pythonsweb

#Pepper: constant appended when hashing password, stored outside of DB, as opposed to a salt which is unique to each password and stored within DB:
#This is randomly generated once at the first init of login/loginHandler.php, and used forevermore:
Cryptographic pepper:
     fe3136f2501e8eb46436917d16bb9b7394bb23291ce3da3f5b6168ea8cd51472cc2c7c37440a88a940c993a1b681cff5fc69c460b15a905df8f74e81d2caf095

#Footer line which will show up at the bottom of the webpage
#Change this to whatever you like:
Footer:
    © Luka Simpson, 2020. All rights reserved. Made using <a href="http://phpqrcode.sourceforge.net/">phpqrcode</a>, which is liscenced under the <a href="https://www.gnu.org/licenses/lgpl-3.0.html">GNU LGPL</a>.

#The customisable navbar:
Navbar:
    Page_1: #The title, has no link
        text:
            Python's Web
        link:
            
    Page_2: #Will log users in and out, don't try to put content here
        text:
            Register/Login
        link:
            index.php?page=2
    Page_3: #The share with class function, again not for content
        text:
            Share With Class
        link:
            index.php?page=3
    Page_4: #search bar, last not-for-content link
        text:
            Search
        link:
            index.php?page=4
    Page_5:
        text:
            Coursework
        link:
            index.php?page=5
    Page_6:
        text:
            Donate
        link:
            index.php?page=6
    Page_7:
        text:
            News
        link:
            index.php?page=7
    Page_8:
        text:
            F. A. Q.
        link:
            index.php?page=8
    Page_9:
        text:
            References
        link:
            index.php?page=9
...